Testing Linux

diff --git a/.github/workflows/linux.yml b/.github/workflows/linux.yml
--- a/.github/workflows/linux.yml
+++ b/.github/workflows/linux.yml
@@ -7,8 +7,37 @@ jobs:
     name: Successful case
     steps:
     - uses: actions/checkout@v2
+    - name: install crash handler
+      shell: bash
+      run: |
+        pip install -r requirements.txt
+        sudo `which python` linuxrunner.py -i
     - name: build testapp
       run: |
         gcc -o testapp -O0 -g testapp.c
     - name: run
-      run: ./testapp -t 5
+      run: python linuxrunner.py -- ./testapp -t 5
+
+  crash-case:
+    runs-on: ubuntu-latest
+    name: Crash case
+    steps:
+    - uses: actions/checkout@master
+    - name: install crash handler
+      shell: bash
+      run: |
+        pip install -r requirements.txt
+        sudo `which python` linuxrunner.py -i
+    - name: build testapp
+      run: |
+        gcc -o testapp -O0 -g testapp.c
+    - name: run
+      shell: bash
+      run: |
+        # Runner will return non-zero if the test program fails, and this will fail the job.
+        # So use commands below to save return value and set exit code to 0.
+        python linux.py -t 60 -- ./testapp -t 5; ret=$?; true
+        if test $ret -eq 0; then
+          false
+        fi
+
