Fixing mac (3)

diff --git a/.github/workflows/macdemo.yml b/.github/workflows/macdemo.yml
--- a/.github/workflows/macdemo.yml
+++ b/.github/workflows/macdemo.yml
@@ -29,14 +29,12 @@ jobs:
       shell: bash
       continue-on-error: true
       run: |
-        ulimit -c unlimited
-        ./testapp -t 5 -c
-    - name: examine crash
-      shell: bash
-      run: |
-        echo ls -l /cores
-        ls -l /cores
-        core=`ls /cores/core.*` | head -1
-        echo core file is $core
-        lldb --core $core -o 'bt all' -o quit ./testapp
+        # Runner will return non-zero if the test program fails, and this will fail the job.
+        # So use commands below to save return value and set exit code to 0.
+        python macrunner.py -t 60 -- ./testapp -t 5 -c; ret=$?; true; true
+        if test $ret -eq 0; then
+          echo Error: expecting failure
+          exit 777
+        fi
+        exit 0
 
