Set correct return value of failed jobs (windows)

diff --git a/.github/workflows/win.yml b/.github/workflows/win.yml
--- a/.github/workflows/win.yml
+++ b/.github/workflows/win.yml
@@ -40,10 +40,10 @@ jobs:
     - name: run
       run: |
         # Runner will return non-zero if the test program fails, but this will fail the job.
-        # So use commands below to save return value to $ret instead.
+        # So use commands below to save return value to $ret and set $lastexitcode to 0.
         python winrunner.py -t 60 -- testapp.exe -t 5 -c; $ret=$lastexitcode; cmd /C exit 0
         if ($ret -eq 0) {
-          cmd /C exit 1
+          cmd /C exit 111
         }
 
   timeout-case:
@@ -65,9 +65,8 @@ jobs:
     - name: run
       run: |
         # Runner will return non-zero if the test program fails, but this will fail the job.
-        # So use commands below to save return value to $ret instead.
-        #python winrunner.py -t 5 -- testapp.exe -t 60; $ret=$lastexitcode; cmd /C exit 0
-        python winrunner.py -- testapp.exe -t 5; $ret=$lastexitcode; cmd /C exit 0
+        # So use commands below to save return value to $ret and set $lastexitcode to 0.
+        python winrunner.py -t 5 -- testapp.exe -t 60; $ret=$lastexitcode; cmd /C exit 0
         if ($ret -eq 0) {
-          cmd /C exit 1
+          cmd /C exit 111
         }
